export const seedMeals = [
  {
    title: 'Chicken rice bowl',
    description: 'A reliable weeknight bowl with rice, greens and a simple sauce.',
    instructions: 'Cook rice. Sear chicken until golden. Steam broccoli. Serve with soy sauce and sesame oil.',
    video_url: '',
    meal_type: 'both',
    prep_time: 25,
    servings: 2,
    price: 7.5,
    tags: ['Healthy', 'High protein'],
    is_public: false,
    ingredients: [
      ['Chicken breast', 600, 'g', 'Protein'],
      ['Rice', 300, 'g', 'Pantry'],
      ['Broccoli', 2, 'heads', 'Produce'],
      ['Soy sauce', 2, 'tbsp', 'Pantry'],
    ],
  },
  {
    title: 'Chickpea curry',
    description: 'Warm pantry curry with coconut and spinach.',
    instructions: 'Soften onion, add spices, chickpeas and coconut milk. Simmer, then fold in spinach. Serve with rice.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 30,
    servings: 3,
    price: 5.2,
    tags: ['Vegetarian', 'Budget'],
    is_public: true,
    ingredients: [
      ['Chickpeas', 2, 'cans', 'Pantry'],
      ['Coconut milk', 1, 'can', 'Pantry'],
      ['Spinach', 200, 'g', 'Produce'],
      ['Rice', 250, 'g', 'Pantry'],
    ],
  },
  {
    title: 'Turkey wraps',
    description: 'Fast lunch with crunchy salad and yogurt sauce.',
    instructions: 'Warm wraps, add turkey, lettuce and yogurt sauce. Roll tightly and slice.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 15,
    servings: 2,
    price: 6.4,
    tags: ['Quick', 'Lunch'],
    is_public: false,
    ingredients: [
      ['Turkey slices', 250, 'g', 'Protein'],
      ['Wraps', 4, 'units', 'Pantry'],
      ['Lettuce', 1, 'head', 'Produce'],
      ['Greek yogurt', 150, 'g', 'Dairy'],
    ],
  },
];

export const publicMeals = [
  {
    title: 'Salmon pasta',
    description: 'Creamy lemon salmon pasta for a quick dinner.',
    instructions: 'Boil pasta. Pan-sear salmon, flake it, then toss with cream, lemon and pasta water.',
    video_url: 'https://www.youtube.com/results?search_query=lemon+salmon+pasta',
    meal_type: 'dinner',
    prep_time: 25,
    servings: 2,
    price: 9.8,
    tags: ['Dinner', 'Protein'],
    creator: 'Marta',
    is_public: true,
    ingredients: [['Salmon', 300, 'g', 'Protein'], ['Pasta', 250, 'g', 'Pantry'], ['Lemon', 1, 'unit', 'Produce'], ['Cream', 150, 'ml', 'Dairy']],
  },
  {
    title: 'Greek salad bowl',
    description: 'Fresh lunch bowl with feta, chickpeas and cucumber.',
    instructions: 'Chop vegetables, rinse chickpeas, crumble feta and dress with olive oil and lemon.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 12,
    servings: 2,
    price: 5.9,
    tags: ['Fresh', 'Vegetarian'],
    creator: 'Tomás',
    is_public: true,
    ingredients: [['Cucumber', 1, 'unit', 'Produce'], ['Tomatoes', 4, 'units', 'Produce'], ['Feta', 150, 'g', 'Dairy'], ['Chickpeas', 1, 'can', 'Pantry']],
  },
  {
    title: 'Tomato basil soup',
    description: 'Simple comfort soup with bread on the side.',
    instructions: 'Roast tomatoes and onion, blend with basil, simmer for 10 minutes and serve with bread.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 35,
    servings: 4,
    price: 4.6,
    tags: ['Budget', 'Comfort'],
    creator: 'Ana',
    is_public: true,
    ingredients: [['Tomatoes', 8, 'units', 'Produce'], ['Onion', 1, 'unit', 'Produce'], ['Basil', 1, 'bunch', 'Produce'], ['Bread', 1, 'loaf', 'Bakery']],
  },
  {
    title: 'Lemon chicken tray bake',
    description: 'One-pan chicken, potatoes and green beans.',
    instructions: 'Add everything to a tray with lemon, garlic and olive oil. Roast until chicken is cooked through.',
    video_url: 'https://www.youtube.com/results?search_query=lemon+chicken+tray+bake',
    meal_type: 'dinner',
    prep_time: 40,
    servings: 4,
    price: 8.2,
    tags: ['One pan', 'Family'],
    creator: 'Sofia',
    is_public: true,
    ingredients: [['Chicken thighs', 800, 'g', 'Protein'], ['Potatoes', 800, 'g', 'Produce'], ['Green beans', 300, 'g', 'Produce'], ['Lemon', 2, 'units', 'Produce']],
  },
  {
    title: 'Peanut tofu noodles',
    description: 'Saucy noodles with tofu and crunchy vegetables.',
    instructions: 'Crisp tofu, boil noodles, whisk peanut sauce and toss everything together.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 22,
    servings: 2,
    price: 6.1,
    tags: ['Vegetarian', 'Quick'],
    creator: 'João',
    is_public: true,
    ingredients: [['Tofu', 300, 'g', 'Protein'], ['Noodles', 220, 'g', 'Pantry'], ['Peanut butter', 3, 'tbsp', 'Pantry'], ['Carrots', 2, 'units', 'Produce']],
  },
  {
    title: 'Tuna avocado toast',
    description: 'High-protein lunch that takes almost no time.',
    instructions: 'Mash avocado with lime, top toast with tuna and season well.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 10,
    servings: 1,
    price: 4.4,
    tags: ['Quick', 'High protein'],
    creator: 'Inês',
    is_public: true,
    ingredients: [['Tuna', 1, 'can', 'Pantry'], ['Avocado', 1, 'unit', 'Produce'], ['Sourdough', 2, 'slices', 'Bakery'], ['Lime', 1, 'unit', 'Produce']],
  },
  {
    title: 'Mushroom risotto',
    description: 'Creamy rice with mushrooms and parmesan.',
    instructions: 'Toast rice, slowly add stock while stirring, fold in mushrooms and finish with parmesan.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 38,
    servings: 3,
    price: 7.1,
    tags: ['Comfort', 'Vegetarian'],
    creator: 'Rita',
    is_public: true,
    ingredients: [['Arborio rice', 300, 'g', 'Pantry'], ['Mushrooms', 400, 'g', 'Produce'], ['Parmesan', 80, 'g', 'Dairy'], ['Vegetable stock', 1, 'l', 'Pantry']],
  },
  {
    title: 'Beef taco bowls',
    description: 'Rice bowls with beef, beans, salsa and lettuce.',
    instructions: 'Cook beef with spices, prepare rice, then layer bowls with beans, lettuce and salsa.',
    video_url: '',
    meal_type: 'both',
    prep_time: 28,
    servings: 4,
    price: 7.9,
    tags: ['Meal prep', 'Family'],
    creator: 'Miguel',
    is_public: true,
    ingredients: [['Ground beef', 600, 'g', 'Protein'], ['Black beans', 2, 'cans', 'Pantry'], ['Rice', 350, 'g', 'Pantry'], ['Lettuce', 1, 'head', 'Produce']],
  },
  {
    title: 'Halloumi couscous salad',
    description: 'Bright lunch with roasted peppers and herbs.',
    instructions: 'Prepare couscous, pan-fry halloumi and toss with peppers, herbs and lemon.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 18,
    servings: 2,
    price: 6.7,
    tags: ['Fresh', 'Vegetarian'],
    creator: 'Laura',
    is_public: true,
    ingredients: [['Halloumi', 200, 'g', 'Dairy'], ['Couscous', 180, 'g', 'Pantry'], ['Roasted peppers', 2, 'units', 'Produce'], ['Parsley', 1, 'bunch', 'Produce']],
  },
  {
    title: 'Shrimp fried rice',
    description: 'Fast rice dinner with peas, egg and shrimp.',
    instructions: 'Stir-fry shrimp, rice, peas and egg in a hot pan with soy sauce.',
    video_url: 'https://www.youtube.com/results?search_query=shrimp+fried+rice',
    meal_type: 'dinner',
    prep_time: 20,
    servings: 2,
    price: 8.6,
    tags: ['Quick', 'Protein'],
    creator: 'Nuno',
    is_public: true,
    ingredients: [['Shrimp', 300, 'g', 'Protein'], ['Rice', 300, 'g', 'Pantry'], ['Eggs', 2, 'units', 'Dairy'], ['Peas', 150, 'g', 'Frozen']],
  },
];
