import { studentRecipeExpansion } from './studentRecipeExpansion';

export const seedMeals = [
  {
    title: 'Chicken rice bowl',
    description: 'A reliable weeknight bowl with rice, greens and a simple sauce.',
    instructions: 'Cook rice. Sear chicken until golden. Steam broccoli. Serve with soy sauce and sesame oil.',
    video_url: '',
    meal_type: 'both',
    prep_time: 25,
    servings: 2,
    price: 7.5,
    tags: ['Healthy', 'High protein'],
    is_public: false,
    ingredients: [
      ['Chicken breast', 600, 'g', 'Protein'],
      ['Rice', 300, 'g', 'Pantry'],
      ['Broccoli', 2, 'heads', 'Produce'],
      ['Soy sauce', 2, 'tbsp', 'Pantry'],
    ],
  },
  {
    title: 'Chickpea curry',
    description: 'Warm pantry curry with coconut and spinach.',
    instructions: 'Soften onion, add spices, chickpeas and coconut milk. Simmer, then fold in spinach. Serve with rice.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 30,
    servings: 3,
    price: 5.2,
    tags: ['Vegetarian', 'Budget'],
    is_public: true,
    ingredients: [
      ['Chickpeas', 2, 'cans', 'Pantry'],
      ['Coconut milk', 1, 'can', 'Pantry'],
      ['Spinach', 200, 'g', 'Produce'],
      ['Rice', 250, 'g', 'Pantry'],
    ],
  },
  {
    title: 'Turkey wraps',
    description: 'Fast lunch with crunchy salad and yogurt sauce.',
    instructions: 'Warm wraps, add turkey, lettuce and yogurt sauce. Roll tightly and slice.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 15,
    servings: 2,
    price: 6.4,
    tags: ['Quick', 'Lunch'],
    is_public: false,
    ingredients: [
      ['Turkey slices', 250, 'g', 'Protein'],
      ['Wraps', 4, 'units', 'Pantry'],
      ['Lettuce', 1, 'head', 'Produce'],
      ['Greek yogurt', 150, 'g', 'Dairy'],
    ],
  },
];

export const publicMeals = [
  {
    title: 'Salmon pasta',
    description: 'Creamy lemon salmon pasta for a quick dinner.',
    instructions: 'Boil pasta. Pan-sear salmon, flake it, then toss with cream, lemon and pasta water.',
    video_url: 'https://www.youtube.com/results?search_query=lemon+salmon+pasta',
    meal_type: 'dinner',
    prep_time: 25,
    servings: 2,
    price: 9.8,
    tags: ['Dinner', 'Protein'],
    creator: 'Marta',
    is_public: true,
    ingredients: [['Salmon', 300, 'g', 'Protein'], ['Pasta', 250, 'g', 'Pantry'], ['Lemon', 1, 'unit', 'Produce'], ['Cream', 150, 'ml', 'Dairy']],
  },
  {
    title: 'Greek salad bowl',
    description: 'Fresh lunch bowl with feta, chickpeas and cucumber.',
    instructions: 'Chop vegetables, rinse chickpeas, crumble feta and dress with olive oil and lemon.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 12,
    servings: 2,
    price: 5.9,
    tags: ['Fresh', 'Vegetarian'],
    creator: 'Tomás',
    is_public: true,
    ingredients: [['Cucumber', 1, 'unit', 'Produce'], ['Tomatoes', 4, 'units', 'Produce'], ['Feta', 150, 'g', 'Dairy'], ['Chickpeas', 1, 'can', 'Pantry']],
  },
  {
    title: 'Tomato basil soup',
    description: 'Simple comfort soup with bread on the side.',
    instructions: 'Roast tomatoes and onion, blend with basil, simmer for 10 minutes and serve with bread.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 35,
    servings: 4,
    price: 4.6,
    tags: ['Budget', 'Comfort'],
    creator: 'Ana',
    is_public: true,
    ingredients: [['Tomatoes', 8, 'units', 'Produce'], ['Onion', 1, 'unit', 'Produce'], ['Basil', 1, 'bunch', 'Produce'], ['Bread', 1, 'loaf', 'Bakery']],
  },
  {
    title: 'Lemon chicken tray bake',
    description: 'One-pan chicken, potatoes and green beans.',
    instructions: 'Add everything to a tray with lemon, garlic and olive oil. Roast until chicken is cooked through.',
    video_url: 'https://www.youtube.com/results?search_query=lemon+chicken+tray+bake',
    meal_type: 'dinner',
    prep_time: 40,
    servings: 4,
    price: 8.2,
    tags: ['One pan', 'Family'],
    creator: 'Sofia',
    is_public: true,
    ingredients: [['Chicken thighs', 800, 'g', 'Protein'], ['Potatoes', 800, 'g', 'Produce'], ['Green beans', 300, 'g', 'Produce'], ['Lemon', 2, 'units', 'Produce']],
  },
  {
    title: 'Peanut tofu noodles',
    description: 'Saucy noodles with tofu and crunchy vegetables.',
    instructions: 'Crisp tofu, boil noodles, whisk peanut sauce and toss everything together.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 22,
    servings: 2,
    price: 6.1,
    tags: ['Vegetarian', 'Quick'],
    creator: 'João',
    is_public: true,
    ingredients: [['Tofu', 300, 'g', 'Protein'], ['Noodles', 220, 'g', 'Pantry'], ['Peanut butter', 3, 'tbsp', 'Pantry'], ['Carrots', 2, 'units', 'Produce']],
  },
  {
    title: 'Tuna avocado toast',
    description: 'High-protein lunch that takes almost no time.',
    instructions: 'Mash avocado with lime, top toast with tuna and season well.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 10,
    servings: 1,
    price: 4.4,
    tags: ['Quick', 'High protein'],
    creator: 'Inês',
    is_public: true,
    ingredients: [['Tuna', 1, 'can', 'Pantry'], ['Avocado', 1, 'unit', 'Produce'], ['Sourdough', 2, 'slices', 'Bakery'], ['Lime', 1, 'unit', 'Produce']],
  },
  {
    title: 'Mushroom risotto',
    description: 'Creamy rice with mushrooms and parmesan.',
    instructions: 'Toast rice, slowly add stock while stirring, fold in mushrooms and finish with parmesan.',
    video_url: '',
    meal_type: 'dinner',
    prep_time: 38,
    servings: 3,
    price: 7.1,
    tags: ['Comfort', 'Vegetarian'],
    creator: 'Rita',
    is_public: true,
    ingredients: [['Arborio rice', 300, 'g', 'Pantry'], ['Mushrooms', 400, 'g', 'Produce'], ['Parmesan', 80, 'g', 'Dairy'], ['Vegetable stock', 1, 'l', 'Pantry']],
  },
  {
    title: 'Beef taco bowls',
    description: 'Rice bowls with beef, beans, salsa and lettuce.',
    instructions: 'Cook beef with spices, prepare rice, then layer bowls with beans, lettuce and salsa.',
    video_url: '',
    meal_type: 'both',
    prep_time: 28,
    servings: 4,
    price: 7.9,
    tags: ['Meal prep', 'Family'],
    creator: 'Miguel',
    is_public: true,
    ingredients: [['Ground beef', 600, 'g', 'Protein'], ['Black beans', 2, 'cans', 'Pantry'], ['Rice', 350, 'g', 'Pantry'], ['Lettuce', 1, 'head', 'Produce']],
  },
  {
    title: 'Halloumi couscous salad',
    description: 'Bright lunch with roasted peppers and herbs.',
    instructions: 'Prepare couscous, pan-fry halloumi and toss with peppers, herbs and lemon.',
    video_url: '',
    meal_type: 'lunch',
    prep_time: 18,
    servings: 2,
    price: 6.7,
    tags: ['Fresh', 'Vegetarian'],
    creator: 'Laura',
    is_public: true,
    ingredients: [['Halloumi', 200, 'g', 'Dairy'], ['Couscous', 180, 'g', 'Pantry'], ['Roasted peppers', 2, 'units', 'Produce'], ['Parsley', 1, 'bunch', 'Produce']],
  },
  {
    title: 'Shrimp fried rice',
    description: 'Fast rice dinner with peas, egg and shrimp.',
    instructions: 'Stir-fry shrimp, rice, peas and egg in a hot pan with soy sauce.',
    video_url: 'https://www.youtube.com/results?search_query=shrimp+fried+rice',
    meal_type: 'dinner',
    prep_time: 20,
    servings: 2,
    price: 8.6,
    tags: ['Quick', 'Protein'],
    creator: 'Nuno',
    is_public: true,
    ingredients: [['Shrimp', 300, 'g', 'Protein'], ['Rice', 300, 'g', 'Pantry'], ['Eggs', 2, 'units', 'Dairy'], ['Peas', 150, 'g', 'Frozen']],
  },
  {
    title: 'Smoky chickpeas on toast',
    description: 'A fast, filling cupboard meal with tomato, paprika and crisp toast.',
    instructions: 'Warm chickpeas with chopped tomatoes, smoked paprika and a splash of water. Simmer until thick, season, then spoon over toast.',
    video_url: '', meal_type: 'both', prep_time: 12, servings: 2, price: 2.8,
    tags: ['Student favourite', 'Budget', 'Quick', 'Vegetarian'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Chickpeas', 1, 'can', 'Pantry'], ['Chopped tomatoes', 1, 'can', 'Pantry'], ['Bread', 4, 'slices', 'Bakery'], ['Smoked paprika', 1, 'tsp', 'Spices']],
  },
  {
    title: 'Microwave shakshuka',
    description: 'Tomatoey eggs made in one bowl when the kitchen is busy.',
    instructions: 'Microwave tomatoes, pepper and paprika until hot. Make two wells, crack in the eggs and microwave in short bursts until the whites are set.',
    video_url: '', meal_type: 'both', prep_time: 10, servings: 1, price: 2.4,
    tags: ['Microwave', 'Budget', 'High protein', 'Vegetarian'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Eggs', 2, 'units', 'Dairy'], ['Chopped tomatoes', 200, 'g', 'Pantry'], ['Red pepper', 0.5, 'unit', 'Produce'], ['Paprika', 1, 'tsp', 'Spices']],
  },
  {
    title: 'Fifteen-minute veggie ramen',
    description: 'Instant comfort upgraded with vegetables, egg and a gingery broth.',
    instructions: 'Simmer noodles and frozen vegetables in stock with ginger and soy sauce. Add a halved boiled egg and spring onion before serving.',
    video_url: '', meal_type: 'dinner', prep_time: 15, servings: 1, price: 2.9,
    tags: ['Exam week', 'Quick', 'One pot', 'Vegetarian'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Noodles', 1, 'pack', 'Pantry'], ['Frozen mixed vegetables', 150, 'g', 'Frozen'], ['Eggs', 1, 'unit', 'Dairy'], ['Vegetable stock', 400, 'ml', 'Pantry']],
  },
  {
    title: 'Cheesy tuna pesto pasta',
    description: 'A dependable store-cupboard pasta that makes excellent leftovers.',
    instructions: 'Boil pasta and peas. Drain, stir through tuna and pesto, top with cheese and grill or cover until melted.',
    video_url: '', meal_type: 'both', prep_time: 25, servings: 3, price: 5.4,
    tags: ['Meal prep', 'Budget', 'High protein'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Pasta', 300, 'g', 'Pantry'], ['Tuna', 2, 'cans', 'Pantry'], ['Pesto', 3, 'tbsp', 'Pantry'], ['Frozen peas', 150, 'g', 'Frozen'], ['Cheddar', 80, 'g', 'Dairy']],
  },
  {
    title: 'Spinach and red lentil dhal',
    description: 'A cheap one-pot curry that freezes well and stretches to four portions.',
    instructions: 'Soften onion with curry powder. Add lentils, tomatoes and water, then simmer until soft. Stir in spinach and season.',
    video_url: '', meal_type: 'dinner', prep_time: 25, servings: 4, price: 4.2,
    tags: ['Batch cook', 'Vegan', 'Budget', 'Freezer friendly'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Red lentils', 250, 'g', 'Pantry'], ['Chopped tomatoes', 1, 'can', 'Pantry'], ['Spinach', 200, 'g', 'Produce'], ['Onion', 1, 'unit', 'Produce'], ['Curry powder', 2, 'tsp', 'Spices']],
  },
  {
    title: 'Freezer black bean quesadillas',
    description: 'Crisp, cheesy wraps that can be assembled ahead and frozen.',
    instructions: 'Mash beans with salsa and spices. Spread over half each wrap, add cheese, fold and toast in a dry pan until crisp.',
    video_url: '', meal_type: 'both', prep_time: 18, servings: 4, price: 4.8,
    tags: ['Freezer friendly', 'Vegetarian', 'Budget', 'Meal prep'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Black beans', 2, 'cans', 'Pantry'], ['Wraps', 8, 'units', 'Bakery'], ['Cheddar', 150, 'g', 'Dairy'], ['Salsa', 150, 'g', 'Pantry']],
  },
  {
    title: 'One-pot tomato chickpea pasta',
    description: 'Pasta, chickpeas and tomato cooked together for minimal washing up.',
    instructions: 'Add pasta, chickpeas, tomatoes, garlic and enough water to a wide pan. Simmer, stirring often, until the pasta is tender and glossy.',
    video_url: '', meal_type: 'dinner', prep_time: 25, servings: 3, price: 4.1,
    tags: ['One pot', 'Vegan', 'Budget'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Pasta', 300, 'g', 'Pantry'], ['Chickpeas', 1, 'can', 'Pantry'], ['Chopped tomatoes', 1, 'can', 'Pantry'], ['Garlic', 2, 'cloves', 'Produce']],
  },
  {
    title: 'Fridge-clearout egg fried rice',
    description: 'The best use for yesterday’s rice and whatever vegetables need eating.',
    instructions: 'Fry vegetables in a hot pan, add cold cooked rice, then push aside and scramble the eggs. Mix with soy sauce.',
    video_url: '', meal_type: 'both', prep_time: 15, servings: 2, price: 3.2,
    tags: ['Leftovers', 'Quick', 'Budget', 'Pantry'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Cooked rice', 400, 'g', 'Pantry'], ['Eggs', 2, 'units', 'Dairy'], ['Frozen mixed vegetables', 200, 'g', 'Frozen'], ['Soy sauce', 2, 'tbsp', 'Pantry']],
  },
  {
    title: 'Big-batch three bean chilli',
    description: 'Six inexpensive portions for rice, wraps, nachos or baked potatoes.',
    instructions: 'Soften onion, add spices, beans and tomatoes, then simmer until thick. Finish with lime or vinegar and divide into portions.',
    video_url: '', meal_type: 'dinner', prep_time: 30, servings: 6, price: 6.3,
    tags: ['Batch cook', 'Vegan', 'Freezer friendly', 'Budget'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Kidney beans', 1, 'can', 'Pantry'], ['Black beans', 1, 'can', 'Pantry'], ['Chickpeas', 1, 'can', 'Pantry'], ['Chopped tomatoes', 2, 'cans', 'Pantry'], ['Onion', 1, 'unit', 'Produce']],
  },
  {
    title: 'Banana overnight oats',
    description: 'A no-cook breakfast prepared in two minutes before bed.',
    instructions: 'Mash half the banana in a jar. Stir in oats, milk and yogurt, chill overnight, then add the remaining banana in the morning.',
    video_url: '', meal_type: 'breakfast', prep_time: 5, servings: 1, price: 1.1,
    tags: ['No cook', 'Meal prep', 'Budget', 'Vegetarian'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Oats', 60, 'g', 'Pantry'], ['Banana', 1, 'unit', 'Produce'], ['Milk', 150, 'ml', 'Dairy'], ['Greek yogurt', 80, 'g', 'Dairy']],
  },
  {
    title: 'Peanut banana porridge',
    description: 'Warm, filling breakfast with inexpensive protein and slow-release energy.',
    instructions: 'Simmer oats with milk until creamy. Stir in peanut butter and top with sliced banana and cinnamon.',
    video_url: '', meal_type: 'breakfast', prep_time: 8, servings: 1, price: 1.25,
    tags: ['Quick', 'Budget', 'High protein', 'Vegetarian'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Oats', 60, 'g', 'Pantry'], ['Milk', 250, 'ml', 'Dairy'], ['Banana', 1, 'unit', 'Produce'], ['Peanut butter', 1, 'tbsp', 'Pantry']],
  },
  {
    title: 'Greek-style butter beans',
    description: 'Creamy beans in tomato sauce with feta and toast for dipping.',
    instructions: 'Simmer butter beans with tomato, oregano and garlic until saucy. Crumble feta over the top and serve with toast.',
    video_url: '', meal_type: 'dinner', prep_time: 25, servings: 2, price: 4.3,
    tags: ['Vegetarian', 'Budget', 'One pot'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Butter beans', 2, 'cans', 'Pantry'], ['Chopped tomatoes', 1, 'can', 'Pantry'], ['Feta', 100, 'g', 'Dairy'], ['Bread', 4, 'slices', 'Bakery']],
  },
  {
    title: 'Sausage and tomato gnocchi',
    description: 'A comforting one-pan dinner with very little preparation.',
    instructions: 'Brown sliced sausages, add gnocchi and tomatoes, then simmer until tender. Stir through spinach before serving.',
    video_url: '', meal_type: 'dinner', prep_time: 20, servings: 3, price: 6.8,
    tags: ['One pan', 'Quick', 'Comfort'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Sausages', 6, 'units', 'Protein'], ['Gnocchi', 500, 'g', 'Pantry'], ['Chopped tomatoes', 1, 'can', 'Pantry'], ['Spinach', 100, 'g', 'Produce']],
  },
  {
    title: 'Ten-minute chicken hummus bowl',
    description: 'A fast lunch assembled from cooked chicken, crunchy vegetables and hummus.',
    instructions: 'Slice the vegetables and chicken. Spoon hummus into bowls, add everything else and finish with lemon and pepper.',
    video_url: '', meal_type: 'lunch', prep_time: 10, servings: 2, price: 6.2,
    tags: ['No cook', 'Quick', 'High protein'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Cooked chicken', 250, 'g', 'Protein'], ['Hummus', 200, 'g', 'Dairy'], ['Cucumber', 1, 'unit', 'Produce'], ['Tomatoes', 3, 'units', 'Produce'], ['Flatbread', 2, 'units', 'Bakery']],
  },
  {
    title: 'Sesame tofu udon',
    description: 'Fast chewy noodles with crisp tofu and frozen green beans.',
    instructions: 'Crisp tofu in a hot pan. Add green beans and udon, then toss with soy sauce, sesame oil and a little chilli.',
    video_url: '', meal_type: 'dinner', prep_time: 20, servings: 2, price: 5.1,
    tags: ['Vegan', 'Quick', 'High protein'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Tofu', 300, 'g', 'Protein'], ['Udon noodles', 400, 'g', 'Pantry'], ['Frozen green beans', 200, 'g', 'Frozen'], ['Soy sauce', 2, 'tbsp', 'Pantry']],
  },
  {
    title: 'Tuna and white bean lunchbox',
    description: 'A protein-rich packed lunch that needs no cooking and travels well.',
    instructions: 'Drain the tuna and beans, then mix with chopped tomato, onion, lemon and olive oil. Pack chilled.',
    video_url: '', meal_type: 'lunch', prep_time: 10, servings: 2, price: 4.5,
    tags: ['No cook', 'Packed lunch', 'High protein', 'Meal prep'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Tuna', 1, 'can', 'Pantry'], ['White beans', 1, 'can', 'Pantry'], ['Tomatoes', 2, 'units', 'Produce'], ['Lemon', 1, 'unit', 'Produce']],
  },
  {
    title: 'Microwave loaded potato',
    description: 'A fluffy potato loaded with beans and cheese in less time than delivery.',
    instructions: 'Pierce the potato and microwave until soft, turning halfway. Split, fluff and top with hot beans, cheese and yogurt.',
    video_url: '', meal_type: 'both', prep_time: 12, servings: 1, price: 2.2,
    tags: ['Microwave', 'Budget', 'Vegetarian', 'Exam week'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Baking potato', 1, 'large', 'Produce'], ['Baked beans', 0.5, 'can', 'Pantry'], ['Cheddar', 40, 'g', 'Dairy'], ['Greek yogurt', 1, 'tbsp', 'Dairy']],
  },
  {
    title: 'Meal-prep burrito bowls',
    description: 'Four colourful lunches built from rice, beans, corn and salsa.',
    instructions: 'Cook the rice and season the beans. Divide between containers with corn and salsa; keep yogurt separate until serving.',
    video_url: '', meal_type: 'both', prep_time: 25, servings: 4, price: 6.4,
    tags: ['Meal prep', 'Budget', 'Vegetarian', 'Packed lunch'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Rice', 300, 'g', 'Pantry'], ['Black beans', 2, 'cans', 'Pantry'], ['Sweetcorn', 1, 'can', 'Pantry'], ['Salsa', 200, 'g', 'Pantry'], ['Greek yogurt', 150, 'g', 'Dairy']],
  },
  {
    title: 'Red lentil tomato soup',
    description: 'A smooth, filling soup made from inexpensive cupboard staples.',
    instructions: 'Soften onion and carrot, add lentils, tomatoes and stock, then simmer until tender. Blend or leave chunky and season.',
    video_url: '', meal_type: 'both', prep_time: 30, servings: 4, price: 3.6,
    tags: ['Batch cook', 'Vegan', 'Freezer friendly', 'Budget'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['Red lentils', 200, 'g', 'Pantry'], ['Chopped tomatoes', 1, 'can', 'Pantry'], ['Carrots', 2, 'units', 'Produce'], ['Onion', 1, 'unit', 'Produce'], ['Vegetable stock', 800, 'ml', 'Pantry']],
  },
  {
    title: 'Pesto white bean wraps',
    description: 'Creamy beans, pesto and salad wrapped into a fast campus lunch.',
    instructions: 'Lightly mash the beans with pesto and lemon. Spread over wraps, add spinach and tomato, then roll tightly.',
    video_url: '', meal_type: 'lunch', prep_time: 10, servings: 2, price: 3.9,
    tags: ['No cook', 'Packed lunch', 'Vegetarian', 'Quick'], creator: 'tryPan Student Kitchen', is_public: true,
    ingredients: [['White beans', 1, 'can', 'Pantry'], ['Wraps', 4, 'units', 'Bakery'], ['Pesto', 2, 'tbsp', 'Pantry'], ['Spinach', 80, 'g', 'Produce'], ['Tomatoes', 2, 'units', 'Produce']],
  },
  ...studentRecipeExpansion,
];
